local function doc_lines(lines, doc)
    for _, text in ipairs(doc or {}) do
        table.insert(lines, text == "" and "---" or "---" .. text)
    end
end

-- Parameters stay optional and untyped unless a type is known, so valid calls never warn.
local function param_lines(lines, signature)
    local names = {}
    for _, name in ipairs(signature and signature.params or {}) do
        table.insert(lines, "---@param " .. name .. "? any")
        table.insert(names, name)
    end
    if signature == nil or signature.vararg then
        table.insert(lines, "---@param ... any")
        table.insert(names, "...")
    end
    return table.concat(names, ", ")
end

-- Renders a function stub such as `function os.cp(srcpath, dstpath, opt) end`.
function stub(qualified, signature, doc, keyword)
    local lines = {}
    doc_lines(lines, doc)
    local params = param_lines(lines, signature)
    if signature == nil or signature.returns then
        table.insert(lines, "---@return any ...")
    end
    table.insert(lines, (keyword or "function") .. " " .. qualified .. "(" .. params .. ") end")
    return table.concat(lines, "\n")
end

-- Renders the header every generated file starts with.
function header(name)
    local version = xmake.version()
    return string.format(
        "---@meta %s\n-- Generated by xmake-luals from xmake %d.%d.%d. Do not edit.",
        name,
        version:major(),
        version:minor(),
        version:patch()
    )
end

-- Returns an identifier for a module name segment.
function identifier(name)
    local result = name:gsub("[^%w_]", "_")
    if result:match("^%d") then
        result = "_" .. result
    end
    return result
end
